# Generated by Django 2.1.2 on 2019-10-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rabbitmq_password',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rabbitmq_queue_limit',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='rabbitmq_username',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
