# Generated by Django 2.1.11 on 2019-11-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20191011_2343'),
    ]

    operations = [
        # migrations.AlterModelManagers(
        #     name='user',
        #     managers=[
        #         ('objects', profiles.models.ChaHubUserManager()),
        #     ],
        # ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
