# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170828_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
