# Generated by Django 2.1.2 on 2019-05-20 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190423_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30, unique=True)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=100, null=True)),
                ('gravatar_id', models.CharField(blank=True, max_length=100, null=True)),
                ('html_url', models.URLField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, max_length=2000, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('node_id', models.CharField(default='', max_length=50, unique=True)),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('followers_url', models.URLField(blank=True, max_length=100, null=True)),
                ('following_url', models.URLField(blank=True, max_length=100, null=True)),
                ('gists_url', models.URLField(blank=True, max_length=100, null=True)),
                ('starred_url', models.URLField(blank=True, max_length=100, null=True)),
                ('subscriptions_url', models.URLField(blank=True, max_length=100, null=True)),
                ('organizations_url', models.URLField(blank=True, max_length=100, null=True)),
                ('repos_url', models.URLField(blank=True, max_length=100, null=True)),
                ('events_url', models.URLField(blank=True, max_length=100, null=True)),
                ('received_events_url', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='github_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='profiles.GithubUserInfo'),
        ),
    ]
