# Generated by Django 2.2.13 on 2020-11-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_user_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_forum_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organizer_direct_message_updates',
            field=models.BooleanField(default=True),
        ),
    ]
