# Generated by Django 2.2.13 on 2020-11-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_user_organizer_direct_message_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_forum_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
