# Generated by Django 2.2.13 on 2020-11-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='linked_in_url',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='personal_website_url',
            new_name='personal_url',
        ),
    ]
