# Generated by Django 2.2.13 on 2020-12-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_forum_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='organizer_direct_message_updates',
            field=models.BooleanField(default=True),
        ),
    ]
