# Generated by Django 2.2.13 on 2020-12-22 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.data
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20201201_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('PARTICIPANT', 'Participant'), ('MEMBER', 'Member'), ('INVITED', 'Invited')], default='INVITED')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'ordering': ['date_joined'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='allow_organization_invite_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=utils.data.PathWrapper('organization_photos'))),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_record', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='organizations', through='profiles.Membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
