# Generated by Django 2.2.13 on 2020-12-10 01:04

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20201207_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['date_joined']},
        ),
        migrations.AddField(
            model_name='membership',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='organization',
            name='user_record',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.TextField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('PARTICIPANT', 'Participant'), ('MEMBER', 'Member'), ('INVITED', 'Invited')], default='INVITED'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
