# Generated by Django 2.2.13 on 2020-12-30 00:34

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import utils.data
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20201219_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['date_joined']},
        ),
        migrations.AddField(
            model_name='membership',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='user_record',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_organization_invite_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.TextField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('PARTICIPANT', 'Participant'), ('MEMBER', 'Member'), ('INVITED', 'Invited')], default='INVITED'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.data.PathWrapper('organization_photos')),
        ),
    ]
