# Generated by Django 2.2.13 on 2020-12-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201229_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_url',
            field=models.URLField(blank=True, error_messages={'invalid': 'This value must be an integer.'}, null=True),
        ),
    ]
