# Generated by Django 2.2.13 on 2020-12-10 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201210_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
