# Generated by Django 2.2.17 on 2023-11-22 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20230902_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quota',
            field=models.BigIntegerField(default=settings.DEFAULT_USER_QUOTA),
        ),
    ]
