# Generated by Django 2.2.17 on 2024-03-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_configurations', '0001_initial'),
        ('profiles', '0012_user_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_created_using_oidc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='oidc_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_users', to='oidc_configurations.Auth_Organization'),
        ),
    ]
