# Generated by Django 2.2.28 on 2025-02-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_deleteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
