# Generated by Django 2.2.28 on 2025-06-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_deleteduser_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='chahub_data_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chahub_needs_retry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chahub_timestamp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
    ]
