# Generated by Django 2.2.28 on 2025-06-23 17:19

from django.db import migrations
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20250623_1341'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', profiles.models.CodabenchUserManager()),
            ],
        ),
    ]
