# Generated by Django 3.2 on 2025-12-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_user_is_banned'),
        ('profiles', '0018_auto_20250623_1719'),
    ]

    operations = [
    ]
