# Generated by Django 3.2 on 2025-12-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_merge_0017_user_is_banned_0018_auto_20250623_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quota',
            field=models.BigIntegerField(default=15, help_text='Size in GB'),
        ),
    ]
