# Generated by Django 4.2.25 on 2025-12-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_alter_deleteduser_id_alter_githubuserinfo_id_and_more"),
        ("profiles", "0019_merge_0017_user_is_banned_0018_auto_20250623_1719"),
    ]

    operations = []
