# Generated by Django 4.2.25 on 2026-01-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_alter_user_quota"),
        ("profiles", "0020_merge_20251212_0942"),
    ]

    operations = []
