# Generated by Django 4.2.25 on 2026-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_merge_0020_alter_user_quota_0020_merge_20251212_0942"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_create_competition",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Leave blank to inherit the global competition creation default.",
                null=True,
            ),
        ),
    ]
