# Generated by Django 5.2.14 on 2026-06-15 08:30

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0021_merge_0020_alter_user_quota_0020_merge_20251212_0942'),
        ('queues', '0002_alter_queue_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('queue', models.ForeignKey(blank=True, help_text='Queue Foreign Key on group model for multiple submissions routing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_groups', to='queues.queue', verbose_name='Groups_for_queue')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
