# Generated by Django 5.2.13 on 2026-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_customgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rabbitmq_queue_limit',
            field=models.PositiveIntegerField(blank=True, default=10),
        ),
    ]
