# Generated by Django 5.2.13 on 2026-08-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_user_rabbitmq_queue_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_bot',
        ),
    ]
