# Generated by Django 5.2.17 on 2026-10-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_remove_user_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='is_selectable_by_participant',
            field=models.BooleanField(default=False, help_text="If checked, participants can choose whether to submit to this group's queue. If unchecked, the group is always active.", verbose_name='Show group selection for participant'),
        ),
    ]
