# Generated by Django 5.2.13 on 2026-08-21 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('platform_type', models.CharField(choices=[('codabench', 'Codabench instance'), ('codalab', 'CodaLab instance')], max_length=32)),
                ('competitions_fetch_url', models.URLField(help_text='API URL used to fetch the list of competitions from this platform')),
                ('competition_base_url', models.URLField(help_text='Base URL used to build links back to individual competitions on this platform')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive platforms are skipped by the fetch task')),
                ('created_when', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_when', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial success'), ('FAILURE', 'Failure')], default='RUNNING', max_length=16)),
                ('total_fetched', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('deleted_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='external_competitions.externalplatform')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('organizer_name', models.CharField(blank=True, default='', max_length=255)),
                ('competition_url', models.URLField(help_text='Link to the competition on its source platform', unique=True)),
                ('competition_created_when', models.DateTimeField(blank=True, help_text='When the competition was created on its source platform', null=True)),
                ('competition_started_when', models.DateTimeField(blank=True, help_text='When the competition starts/started on its source platform', null=True)),
                ('created_when', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_when', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='external_competitions.externalplatform')),
            ],
        ),
    ]
