# Generated by Django 2.2.17 on 2023-06-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
