# Generated by Django 2.2.17 on 2023-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20230615_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
