# Generated by Django 4.2.23 on 2025-09-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0003_auto_20230616_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="newspost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
