# Generated by Django 5.2.17 on 2026-09-30 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_id_alter_newspost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='level',
            field=models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('plain', 'Plain')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Lower priority is shown first.'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
