# Generated by Django 5.2.17 on 2026-10-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcement_created_when_announcement_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='placement',
            field=models.CharField(choices=[('home_page', 'Home page'), ('platform', 'All pages')], default='home_page', help_text='Home page: shown on the home page only. All pages: shown in a banner above the header on every page.', max_length=20),
        ),
    ]
