# TODO: Do some of these..!
#    # Check templates and such for style= attributes
#    - if [[ `grep -rnw src/templates/ -e 'style='` ]]; then (exit -1); fi
#    - if [[ `grep -rnw src/static/riot -e 'style='` ]]; then (exit -1); fi
#    # - if [[ `grep -rnw src -e 'TODO'` ]]; then (exit -1); fi

version: 2

jobs:
  test:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run: cp .env_circleci .env

      - run:
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.selenium.yml up -d
            docker-compose -f docker-compose.yml -f docker-compose.selenium.yml exec django python manage.py collectstatic --noinput
            docker-compose -f docker-compose.yml -f docker-compose.selenium.yml exec django py.test src/tests/functional/ -m e2e

      - store_artifacts:
          path: artifacts/

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
