version: 2

jobs:
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout

      - run:
          # NOTE: To connect to this, use an SSH tunnel in front, like so..
          #
          #     In one terminal:
          #         $ ssh -p PORT ubuntu@CIRCLE_IP_ADDRESS -L 5900:localhost:5900
          #
          #     In another terminal:
          #         $ open vnc://0.0.0.0:5900
          name: Download and start X for VNC viewing
          command: |
            sudo apt-get install -y x11vnc
            x11vnc -forever -nopw
          background: true

      - run: cp .env_circleci .env


      - run:
          name: Making gross directories for minio, cannot be made by docker for some reason
          command: |
            sudo mkdir -p var/minio/public
            sudo mkdir -p var/minio/private

      - run:
          name: Build containers and collect static
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.selenium.yml up -d
            docker-compose -f docker-compose.yml -f docker-compose.selenium.yml exec django python manage.py collectstatic --noinput

      - run:
          name: pytest
          command: docker-compose -f docker-compose.yml -f docker-compose.selenium.yml exec django py.test src/ -m "not e2e"

      - run:
          name: e2e tests
          command: docker-compose -f docker-compose.yml -f docker-compose.selenium.yml exec django py.test src/tests/functional/ -m e2e
          no_output_timeout: 60m

      - run: docker-compose exec django flake8 src/ --ignore E501,F405

      - store_artifacts:
          path: artifacts/

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
