FROM python:3.10

RUN apt-get update && apt-get install -y gcc build-essential && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED 1

RUN curl -sSL https://install.python-poetry.org | python3 -
# add poetry to PATH
# RUN export PATH=$PATH:/root/.local/bin

# RUN poetry config virtualenvs.create false
# RUN poetry config virtualenvs.in-project false
# RUN poetry config package-mode false
# RUN poetry install

# poetry add django-redis-cache="^2.13.0"

# ADD requirements.dev.txt .
# ADD requirements.txt .
# RUN pip install -U pip
# RUN pip install -r requirements.dev.txt

WORKDIR /app
