FROM ubuntu:20.04

# Update
RUN apt update -y;

# Install tools for other installs
RUN apt-get install -y wget curl gpg systemctl

# Install Docker
RUN curl -fsSL https://get.docker.com | sh

# Nvidia Container Toolkit for cuda use with docker
# [source](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)

RUN curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
    && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

RUN apt-get update -y;
RUN apt-get install -y nvidia-container-toolkit

# Make it explicit that we're using GPUs
# BB - not convinced we need this
ENV NVIDIA_DOCKER 1 


# Install python pending...
## I suggest pyenv by maybe just some stock newish python is all we need as we really just need celery

CMD ['bash']
