FROM python:3
ENV PYTHONUNBUFFERED 1
ENV C_FORCE_ROOT True
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r requirements.txt
#ADD . /code/
CMD ["celery", "-A", "src.comp_worker", "worker", "--loglevel=debug"]