{{- with .Values.caddy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: "{{ .image.repository }}:{{ .image.tag }}"
          env:
            - name: ACME_AGREE
              value: True
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
            - name: staticfiles
              mountPath: /var/www/django/static
            - name: caddydata
              mountPath: /data
            - name: caddyconfig
              mountPath: /config
            - name: caddylog
              mountPath: /var/log/
          ports:
            - containerPort: 80
            - containerPort: 443
      volumes:
        - name: caddyfile
          emptyDir: {}
        - name: staticfiles
          emptyDir: {}
        - name: caddydata
          emptyDir: {}
        - name: caddyconfig
          emptyDir: {}
        - name: caddylog
          emptyDir: {}
{{- end }}
