{{- with .Values.minio }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: "{{ .image.repository }}:{{ .image.tag }}"
          command: ["server", "/export"]
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: MINIO_SECRET_KEY
          volumeMounts:
            - name: export
              mountPath: /export
          ports:
            - containerPort: 9000
          livenessProbe:
            exec:
              command: ["nc", "-z", "minio", "9000"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: export
          emptyDir: {}
{{- end }}
