{{- with .Values.minio }}
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-buckets
spec:
  template:
    spec:
      initContainers:
      - name: init-wait-for-minio
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          until nc -z -v -w30 minio 9000
          do
            echo "Waiting for MinIO service..."
            sleep 5
          done
          echo "MinIO is up and running!"
      containers:
      - name: main-job
        image: minio/mc
        env:
          - name: MINIO_PORT
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: MINIO_PORT
          - name: AWS_STORAGE_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: AWS_STORAGE_BUCKET_NAME
          - name: AWS_STORAGE_PRIVATE_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: AWS_STORAGE_PRIVATE_BUCKET_NAME
          - name: MINIO_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: MINIO_ACCESS_KEY
          - name: MINIO_SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: MINIO_SECRET_KEY
        command:
        - /bin/sh
        - -c
        - |
          set -x;
          if [ -n \"$MINIO_ACCESS_KEY\" ] && [ -n \"$MINIO_SECRET_KEY\" ] && [ -n \"$MINIO_PORT\" ]; then
            until /usr/bin/mc config host add minio_docker http://minio:$MINIO_PORT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY && break; do 
              echo '...waiting...' && sleep 5; 
            done;
            /usr/bin/mc mb minio_docker/$AWS_STORAGE_BUCKET_NAME || echo 'Bucket $AWS_STORAGE_BUCKET_NAME already exists.';
            /usr/bin/mc mb minio_docker/$AWS_STORAGE_PRIVATE_BUCKET_NAME || echo 'Bucket $AWS_STORAGE_PRIVATE_BUCKET_NAME already exists.';
            /usr/bin/mc anonymous set download minio_docker/$AWS_STORAGE_BUCKET_NAME;
          else
            echo 'MINIO_ACCESS_KEY, MINIO_SECRET_KEY, or MINIO_PORT are not defined. Skipping buckets creation.';
          fi;
          exit 0;
      restartPolicy: Never
{{- end }}
