apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.env.RABBITMQ_DEFAULT_PASS | b64enc }}
  FLOWER_BASIC_AUTH: {{ .Values.env.FLOWER_BASIC_AUTH | b64enc }}
