# Generated by Django 2.1.2 on 2019-02-14 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0007_auto_20190214_1845'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingestionmodule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ingestionmodule',
            name='ingestion_program',
        ),
        migrations.RemoveField(
            model_name='ingestionmodule',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='scoringmodule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scoringmodule',
            name='reference_data',
        ),
        migrations.RemoveField(
            model_name='scoringmodule',
            name='scoring_program',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ingestion_module',
        ),
        migrations.RemoveField(
            model_name='task',
            name='scoring_module',
        ),
        migrations.AddField(
            model_name='task',
            name='ingestion_only_during_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='ingestion_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_ingestion_programs', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='task',
            name='input_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_input_datas', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='task',
            name='reference_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reference_datas', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='task',
            name='scoring_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_scoring_programs', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='IngestionModule',
        ),
        migrations.DeleteModel(
            name='ScoringModule',
        ),
    ]
