# Generated by Django 2.1.2 on 2019-10-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='chahub_data_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='chahub_needs_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solution',
            name='chahub_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='chahub_data_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='chahub_needs_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='chahub_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
