# Generated by Django 2.1.11 on 2019-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191016_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
