# Generated by Django 2.2.13 on 2020-09-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('tasks', '0003_task_order'), ('tasks', '0004_remove_task_order')]

    dependencies = [
        ('tasks', '0002_auto_20191203_1911'),
    ]

    operations = [
    ]
