# Generated by Django 2.1.2 on 2019-01-16 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190111_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
