# Generated by Django 2.1.2 on 2019-04-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190214_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='name',
            field=models.CharField(default='solution', max_length=256),
            preserve_default=False,
        ),
    ]
