# Generated by Django 2.1.2 on 2019-07-23 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190417_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasets.Data'),
        ),
    ]
