# Generated by Django 2.1.11 on 2019-11-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_solution_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
