# Generated by Django 2.1.2 on 2019-01-17 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0007_auto_20190116_2044'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20190116_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('key', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('only_during_scoring', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ingestion_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_ingestion_programs', to='datasets.Data')),
                ('input_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_input_datas', to='datasets.Data')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('key', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('reference_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reference_datas', to='datasets.Data')),
                ('scoring_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_scoring_programs', to='datasets.Data')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='ingestion_program',
        ),
        migrations.RemoveField(
            model_name='task',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reference_data',
        ),
        migrations.RemoveField(
            model_name='task',
            name='scoring_program',
        ),
        migrations.AddField(
            model_name='task',
            name='ingestion_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.IngestionModule'),
        ),
        migrations.AddField(
            model_name='task',
            name='scoring_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.ScoringModule'),
        ),
    ]
