# Generated by Django 2.2.13 on 2020-10-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_private',
        ),
    ]
