# Generated by Django 2.1.11 on 2019-11-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20191122_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='md5',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
