# Generated by Django 2.2.28 on 2025-06-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='chahub_data_hash',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='chahub_needs_retry',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='chahub_timestamp',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='chahub_data_hash',
        ),
        migrations.RemoveField(
            model_name='task',
            name='chahub_needs_retry',
        ),
        migrations.RemoveField(
            model_name='task',
            name='chahub_timestamp',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deleted',
        ),
    ]
