# Generated by Django 4.2.25 on 2025-12-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_solution_id_alter_task_id"),
        ("tasks", "0005_auto_20250623_1341"),
    ]

    operations = []
