# Generated by Django 2.1.2 on 2019-10-11 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('vhost', models.UUIDField(unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('organizers', models.ManyToManyField(blank=True, help_text='(Organizers allowed to view this queue when they assign their competition to a queue)', related_name='organizers', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='queues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
