# Generated by Django 2.1.2 on 2019-10-15 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='organizers',
            field=models.ManyToManyField(blank=True, help_text='(Organizers allowed to view this queue when they assign their competition to a queue)', related_name='organized_queues', to=settings.AUTH_USER_MODEL),
        ),
    ]
