# Generated by Django 2.0.1 on 2018-01-25 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computation', models.TextField(blank=True, choices=[('AVG', 'Average')], null=True)),
                ('title', models.CharField(max_length=36)),
                ('key', models.CharField(max_length=36)),
                ('sorting', models.TextField(choices=[('desc', 'Descending'), ('asc', 'Ascending')], default=('desc', 'Descending'))),
                ('index', models.PositiveIntegerField()),
                ('computation_columns', models.ManyToManyField(to='leaderboards.Column')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=36)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition')),
                ('primary_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaderboards.Column')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=10, max_digits=20)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Column')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.Submission')),
            ],
        ),
    ]
