# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='column_count',
            field=models.IntegerField(default=0),
        ),
    ]
