# Generated by Django 2.0.1 on 2018-01-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='leaderboard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='leaderboards.Leaderboard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='primary_column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primaries', to='leaderboards.Column'),
        ),
    ]
