# Generated by Django 2.1.11 on 2019-12-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_auto_20191220_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
