# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_leaderboard_column_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='leaderboards.Leaderboard'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(default='new_metric', max_length=50),
        ),
    ]
