# Generated by Django 2.2.9 on 2020-02-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_auto_20191226_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
