# Generated by Django 2.2.13 on 2020-08-10 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_leaderboard_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='competition',
        ),
    ]
