# Generated by Django 2.2.13 on 2020-07-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191203_1911'),
        ('leaderboards', '0003_leaderboard_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionscore',
            options={'ordering': ('task__pk',)},
        ),
        migrations.AddField(
            model_name='submissionscore',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.Task'),
        ),
    ]
