# Generated by Django 2.2.10 on 2020-07-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_leaderboard_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionscore',
            options={'ordering': ('task_pk',)},
        ),
        migrations.AddField(
            model_name='submissionscore',
            name='task_pk',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
