# Generated by Django 2.0.1 on 2018-01-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_auto_20180126_1719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('leaderboard', 'key')},
        ),
    ]
