# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_auto_20180103_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='main_column',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_leaderboard', to='leaderboards.Column'),
        ),
    ]
