# Generated by Django 2.2.10 on 2020-07-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0004_auto_20200703_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionscore',
            name='task_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
