# Generated by Django 2.0.1 on 2018-01-22 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0004_leaderboard_main_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='name',
        ),
        migrations.AlterField(
            model_name='column',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='columns', to='leaderboards.Leaderboard'),
        ),
        migrations.AlterField(
            model_name='column',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='columns', to='leaderboards.Metric'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='competition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leaderboard', to='competitions.Competition'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='main_column',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_leaderboard', to='leaderboards.Column'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_metrics', to=settings.AUTH_USER_MODEL),
        ),
    ]
