# Generated by Django 2.2.13 on 2020-11-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0006_auto_20201021_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='submission_rule',
            field=models.TextField(choices=[('Add', 'Only allow adding one submission'), ('Add_And_Delete', 'Allow users to add a single submission and remove that submission'), ('Add_And_Delete_Multiple', 'Allow users to add a multiple submissions and remove those submission'), ('Force_Last', 'Force only the last submission'), ('Force_Latest_Multiple', 'Force latest submission to be added to leaderboard (multiple)'), ('Force_Best', 'Force only the best submission to the leaderboard')], default='Add'),
        ),
    ]
