# Generated by Django 2.2.13 on 2020-07-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0006_auto_20200707_0542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionscore',
            options={'ordering': ('task',)},
        ),
        migrations.AlterField(
            model_name='submissionscore',
            name='task',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
