# Generated by Django 2.1.2 on 2018-11-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0007_leaderboard_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='submissions',
        ),
    ]
