# Generated by Django 2.2.17 on 2023-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0007_auto_20201110_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionscore',
            name='score',
            field=models.CharField(max_length=2),
        ),
    ]
