# Generated by Django 2.2.17 on 2023-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0007_auto_20201110_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='precision',
            field=models.IntegerField(default=2),
        ),
    ]
