# Generated by Django 2.2.17 on 2023-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0008_column_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='test_column',
            field=models.IntegerField(default=0),
        ),
    ]
