# Generated by Django 2.1.2 on 2019-06-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0008_remove_leaderboard_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionscore',
            name='submission',
        ),
    ]
