# Generated by Django 2.2.17 on 2023-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0008_column_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='label',
            field=models.CharField(default='', max_length=36),
        ),
    ]
