# Generated by Django 3.2 on 2025-08-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0008_column_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='computation',
            field=models.TextField(blank=True, choices=[('avg', 'Average'), ('sum', 'Sum'), ('min', 'Min'), ('max', 'Max'), ('avg_rank', 'Average rank')], null=True),
        ),
    ]
