# Generated by Django 2.1.2 on 2019-08-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0009_remove_submissionscore_submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('index',)},
        ),
    ]
