# Generated by Django 2.2.17 on 2023-04-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0009_auto_20230405_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionscore',
            name='score',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
