# Generated by Django 5.2.12 on 2026-04-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0009_alter_column_id_alter_leaderboard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='computation',
            field=models.TextField(blank=True, choices=[('avg', 'Average'), ('sum', 'Sum'), ('min', 'Min'), ('max', 'Max'), ('avg_rank', 'Average Rank')], null=True),
        ),
    ]
