# Generated by Django 2.2.17 on 2023-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0010_auto_20230405_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionscore',
            name='score',
            field=models.CharField(max_length=10),
        ),
    ]
