# Generated by Django 2.2.17 on 2023-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0011_auto_20230406_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionscore',
            name='score',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
