# Generated by Django 2.2.17 on 2023-04-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0012_auto_20230406_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionscore',
            name='precision',
            field=models.IntegerField(default=2),
        ),
    ]
