# Generated by Django 2.2.17 on 2023-04-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0013_submissionscore_precision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionscore',
            name='precision',
        ),
        migrations.AddField(
            model_name='column',
            name='precision',
            field=models.IntegerField(default=2),
        ),
    ]
