# Generated by Django 5.2.17 on 2026-10-02 07:02

import django.db.models.deletion
import django.utils.timezone
import utils.data
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to=utils.data.PathWrapper('consulting'))),
                ('website_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(help_text='Markdown')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Shown to the owner when the listing is rejected')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive listings are hidden from the public list, even when approved')),
                ('created_when', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_when', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulting_listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
