FROM almalinux:10-minimal
RUN microdnf install -y tar gzip

ENV PYTHONUNBUFFERED=1

# Install UV and add paths to PATH for uv and the future .venv created by uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH=$PATH:/root/.local/bin
ENV PATH=$PATH:/.venv/bin


COPY pyproject.toml ./
COPY uv.lock ./

# Install dependencies
RUN uv sync --all-extras --frozen


WORKDIR /app
ENTRYPOINT ["/bin/bash", "-c"]
