# Generated by Django 2.1.2 on 2019-09-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboards', '0001_initial'),
        ('datasets', '0001_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='submission',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='leaderboards.Leaderboard'),
        ),
    ]
