# Generated by Django 2.0.1 on 2018-01-25 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='ingestion_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_programs', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='phase',
            name='input_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_datas', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='phase',
            name='public_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_datas', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='phase',
            name='reference_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_datas', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='phase',
            name='scoring_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_programs', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='phase',
            name='starting_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_kits', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='page',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pages', to='competitions.Competition'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to='competitions.Competition'),
        ),
    ]
