# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 01:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0002_phase_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='created_when',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 28, 1, 52, 46, 321706, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
