# Generated by Django 2.1.2 on 2019-10-17 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_auto_20190925_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitioncreationtaskstatus',
            name='resulting_competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creation_statuses', to='competitions.Competition'),
        ),
    ]
