# Generated by Django 2.1.2 on 2019-10-15 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20191015_2058'),
        ('competitions', '0003_auto_20190925_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='queues.Queue'),
        ),
    ]
