# Generated by Django 2.1.11 on 2019-11-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competition_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitioncreationtaskstatus',
            name='resulting_competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creation_statuses', to='competitions.Competition'),
        ),
    ]
