# Generated by Django 2.0.1 on 2018-01-30 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competition_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='number',
            new_name='index',
        ),
    ]
