# Generated by Django 2.0.1 on 2018-01-22 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competitionparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='competition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to='competitions.Competition'),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phase',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='phases', to='competitions.Competition'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissions', to='competitions.Phase'),
        ),
    ]
