# Generated by Django 2.1.11 on 2020-01-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20191218_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
    ]
