# Generated by Django 2.1.11 on 2019-11-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20191118_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
