# Generated by Django 2.1.11 on 2020-01-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20191203_1855'),
        ('competitions', '0006_auto_20200123_1651'),
    ]

    operations = [
    ]
