# Generated by Django 2.1.11 on 2020-01-22 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_remove_submission_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('index',)},
        ),
    ]
