# Generated by Django 2.0.1 on 2018-01-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_auto_20180130_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
