# Generated by Django 2.1.11 on 2019-11-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_submission_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='chahub_data_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='chahub_needs_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='chahub_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
