# Generated by Django 2.0.1 on 2018-01-30 11:04

from django.db import migrations, models
import src.utils.data


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_auto_20180130_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='name',
            field=models.CharField(default='asdf', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(null=True, upload_to=src.utils.data.PathWrapper('logos')),
        ),
    ]
