# Generated by Django 2.2.9 on 2020-02-12 20:01

from django.db import migrations, models
import utils.data

# New
from storages.backends.s3boto3 import S3Boto3Storage


class _MigrationPrivateStorage(S3Boto3Storage):
    bucket_name = 'private'


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20200128_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='enable_detailed_results',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='detailed_result',
            field=models.FileField(blank=True, null=True, storage=_MigrationPrivateStorage(), upload_to=utils.data.PathWrapper('detailed_result')),
        ),
    ]
