# Generated by Django 2.0.1 on 2018-02-07 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20180130_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competitions.CompetitionParticipant'),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
