# Generated by Django 2.0.1 on 2018-02-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_auto_20180205_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='phase',
        ),
    ]
