# Generated by Django 2.2.10 on 2020-02-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_phase_hide_output'),
        ('competitions', '0009_auto_20200212_2001'),
    ]

    operations = [
    ]
