# Generated by Django 2.0.1 on 2018-02-07 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.data


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_auto_20180205_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_when',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competitions.CompetitionParticipant'),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='NONE', max_length=128),
        ),
        migrations.AddField(
            model_name='submission',
            name='track',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.data.PathWrapper('submissions')),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submission', to=settings.AUTH_USER_MODEL),
        ),
    ]
