# Generated by Django 2.0.1 on 2018-02-07 18:33

from django.conf import settings
from django.db import migrations, models
import utils.data


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20180207_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.data.PathWrapper('logos')),
        ),
    ]
