# Generated by Django 2.2.10 on 2020-06-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_merge_20200217_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='allow_robot_submissions',
            field=models.BooleanField(default=False),
        ),
    ]
