# Generated by Django 2.2.13 on 2020-07-06 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaderboards', '0003_leaderboard_hidden'),
        ('competitions', '0010_merge_20200217_2316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('owner', 'leaderboard', 'phase')},
        ),
    ]
