# Generated by Django 2.0.1 on 2018-02-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_remove_submission_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(default='NONE', max_length=128),
        ),
    ]
