# Generated by Django 2.0.1 on 2018-02-07 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_auto_20180207_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_when',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
