# Generated by Django 2.2.10 on 2020-06-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191203_1911'),
        ('competitions', '0010_merge_20200217_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='selected_tasks',
            field=models.ManyToManyField(related_name='submissions', to='tasks.Task'),
        ),
    ]
