# Generated by Django 2.2.10 on 2020-07-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_merge_20200217_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('competition', 'competition'), ('benchmark', 'benchmark')], default='competition', max_length=128),
        ),
    ]
