# Generated by Django 2.2.10 on 2020-07-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191203_1911'),
        ('competitions', '0011_competition_competition_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='task_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.Task'),
        ),
    ]
