# Generated by Django 2.0.1 on 2018-02-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_auto_20180207_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='scoring_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_programs', to='datasets.Data'),
        ),
    ]
