# Generated by Django 2.0.1 on 2018-02-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_auto_20180207_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='public',
            new_name='is_public',
        ),
    ]
