# Generated by Django 2.2.10 on 2020-07-06 23:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_leaderboard_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0011_competition_competition_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('owner', 'leaderboard', 'phase')},
        ),
    ]
