# Generated by Django 2.2.10 on 2020-07-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_auto_20200630_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='task',
            new_name='task_id',
        ),
    ]
