# Generated by Django 2.0.1 on 2018-02-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_auto_20180207_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='competitions.Competition'),
        ),
    ]
