# Generated by Django 2.0.1 on 2018-02-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_auto_20180207_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='track',
            field=models.IntegerField(default=1),
        ),
    ]
