# Generated by Django 2.2.10 on 2020-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_auto_20200706_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='allow_robot_submissions',
            field=models.BooleanField(default=False),
        ),
    ]
