# Generated by Django 2.2.10 on 2020-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_auto_20200706_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='celery_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
