# Generated by Django 2.0.1 on 2018-02-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_submission_status'),
        ('competitions', '0013_submission_track'),
    ]

    operations = [
    ]
