# Generated by Django 2.0.2 on 2018-02-23 04:02

from django.conf import settings
from django.db import migrations, models
import utils.data
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_auto_20180207_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.data.PathWrapper('submissions_output')),
        ),
        migrations.AddField(
            model_name='submission',
            name='scoring_output_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.data.PathWrapper('submissions_scoring_output')),
        ),
        migrations.AddField(
            model_name='submission',
            name='scoring_stderr_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.data.PathWrapper('submissions_scoring_stderr')),
        ),
        migrations.AddField(
            model_name='submission',
            name='scoring_stdout_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.data.PathWrapper('submissions_scoring_stdout')),
        ),
        migrations.AddField(
            model_name='submission',
            name='secret',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='submission',
            name='stderr_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.data.PathWrapper('submissions_stderr')),
        ),
        migrations.AddField(
            model_name='submission',
            name='stdout_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.data.PathWrapper('submissions_stdout')),
        ),
        migrations.AlterField(
            model_name='competition',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='SUBMITTED', max_length=128),
        ),
    ]
