# Generated by Django 2.1 on 2018-08-20 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_auto_20180207_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborations', to=settings.AUTH_USER_MODEL),
        ),
    ]
