# Generated by Django 2.0.2 on 2018-02-09 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_auto_20180207_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
