# Generated by Django 2.2.10 on 2020-07-02 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_auto_20200701_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.Task'),
        ),
    ]
