# Generated by Django 2.2.10 on 2020-07-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_auto_20200702_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='task_id',
            new_name='task',
        ),
    ]
