# Generated by Django 2.1 on 2018-08-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0003_auto_20180820_1920'),
        ('competitions', '0014_auto_20180820_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionCreationTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, choices=[('Starting', 'None'), ('Finished', 'Finished'), ('Failed', 'Failed')], null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_bundles', to='datasets.Data')),
                ('resulting_competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition')),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Failed', 'Failed'), ('None', 'None'), ('Submitted', 'Submitted'), ('Submitting', 'Submitting')], default='None', max_length=128),
        ),
    ]
