# Generated by Django 2.2.10 on 2020-07-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_submission_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='allow_robot_submissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='tasks.Task'),
        ),
    ]
