# Generated by Django 2.0.2 on 2018-02-12 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_auto_20180209_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionparticipant',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.Competition'),
        ),
    ]
