# Generated by Django 2.0.1 on 2018-02-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_merge_20180207_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
