# Generated by Django 2.2.13 on 2020-09-18 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0004_remove_leaderboard_competition'),
        ('competitions', '0015_auto_20200710_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='is_final_phase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phases', to='leaderboards.Leaderboard'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.TextField(blank=True, choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Next', 'Next')], null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='datasets.Data'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
