# Generated by Django 2.2.13 on 2020-08-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_auto_20200724_2354'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
