# Generated by Django 2.2.13 on 2020-09-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_order'),
        ('competitions', '0016_auto_20200724_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='is_final_phase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='phases', to='leaderboards.Leaderboard'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.TextField(blank=True,
                                   choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Next', 'Next')],
                                   null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission',
                                    to='datasets.Data'),
        ),
        migrations.CreateModel(
            name='PhaseTaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=999)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Phase')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
        ),
    ]
