# Generated by Django 2.2.13 on 2020-09-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_order'),
        ('competitions', '0016_auto_20200918_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=999)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Phase')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
        ),
    ]
