# Generated by Django 2.2.13 on 2020-08-10 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0004_remove_leaderboard_competition'),
        ('competitions', '0016_auto_20200724_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leaderboards.Leaderboard'),
        ),
    ]
