# Generated by Django 2.2.13 on 2020-08-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_auto_20200819_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='is_final_phase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.TextField(blank=True, choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Next', 'Next')], null=True),
        ),
    ]
