# Generated by Django 2.2.13 on 2020-08-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_phase_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phases', to='leaderboards.Leaderboard'),
        ),
    ]
