# Generated by Django 2.2.13 on 2020-09-24 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_phasetaskinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitioncreationtaskstatus',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_bundles', to='datasets.Data'),
        ),
    ]
