# Generated by Django 2.2.13 on 2020-10-08 19:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_submission_fact_sheet_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='fact_sheet',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=4096, null=True),
        ),
    ]
