# Generated by Django 2.1 on 2018-10-02 22:05

from django.db import migrations, models
import utils.data


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_auto_20181002_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to=utils.data.PathWrapper('submission_result')),
        ),
    ]
