# Generated by Django 2.1 on 2018-10-04 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_auto_20181002_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='api_key',
            new_name='secret',
        ),
        migrations.AlterField(
            model_name='submission',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Submitting', 'Submitting'), ('Submitted', 'Submitted'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='None', max_length=128),
        ),
    ]
