# Generated by Django 2.1 on 2018-10-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_auto_20181004_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='execution_time_limit',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Submitting', 'Submitting'), ('Submitted', 'Submitted'), ('Running', 'Running'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='None', max_length=128),
        ),
    ]
