# Generated by Django 2.2.13 on 2020-09-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_phase_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phasetaskinstance',
            options={'ordering': ['order_index']},
        ),
    ]
