# Generated by Django 2.1.2 on 2018-10-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_auto_20181005_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
