# Generated by Django 2.2.13 on 2020-09-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0021_auto_20200928_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasetaskinstance',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_instances', to='competitions.Phase'),
        ),
    ]
