# Generated by Django 2.2.13 on 2020-10-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0022_auto_20200930_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
