# Generated by Django 2.2.13 on 2020-10-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0022_auto_20200930_2036'),
        ('competitions', '0018_auto_20200924_0037'),
    ]

    operations = [
    ]
