# Generated by Django 2.1.2 on 2018-11-27 03:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0022_auto_20181008_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Submitting', 'Submitting'), ('Submitted', 'Submitted'), ('Preparing', 'Preparing'), ('Running', 'Running'), ('Scoring', 'Scoring'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='submissiondetails',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='competitions.Submission'),
        ),
    ]
