# Generated by Django 2.2.13 on 2020-10-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0022_auto_20200930_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='leaderboard_mode',
            field=models.CharField(choices=[('manually', 'manually'), ('latest', 'latest'), ('all', 'all'), ('best', 'best')], default='manually', max_length=10),
        ),
    ]
