# Generated by Django 2.1.2 on 2018-11-27 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0008_remove_leaderboard_submissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0023_auto_20181127_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboards.Leaderboard'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('owner', 'leaderboard')},
        ),
    ]
