# Generated by Django 2.2.13 on 2020-10-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_competitioncreationtaskstatus_created_by'),
        ('competitions', '0023_merge_20201013_1628'),
    ]

    operations = [
    ]
