# Generated by Django 2.2.13 on 2020-10-21 23:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0023_auto_20201020_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='fact_sheet',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='fact_sheet_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
