# Generated by Django 2.2.13 on 2020-10-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0023_submission_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_specific_task_re_run',
            field=models.BooleanField(default=False),
        ),
    ]
