# Generated by Django 2.2.13 on 2020-10-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0023_competition_leaderboard_mode'),
        ('competitions', '0023_auto_20201020_0038'),
    ]

    operations = [
    ]
