# Generated by Django 2.1.2 on 2019-01-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('competitions', '0024_auto_20181127_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='is_task_and_solution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases', to='tasks.Solution'),
        ),
        migrations.AddField(
            model_name='phase',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_phases', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='ingestion_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_ingestion_programs', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='input_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_input_datas', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='public_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_public_datas', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='reference_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_reference_datas', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='scoring_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_scoring_programs', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='starting_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_starting_kits', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='leaderboards.Leaderboard'),
        ),
    ]
