# Generated by Django 2.2.13 on 2020-10-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0024_merge_20201021_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='leaderboard_mode',
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
