# Generated by Django 2.1.2 on 2019-01-28 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('competitions', '0024_auto_20181127_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('denied', 'denied'), ('approved', 'approved'), ('pending', 'pending')], default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='phase',
            name='has_max_submissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='is_task_and_solution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='max_submissions_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='max_submissions_per_person',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='solutions',
            field=models.ManyToManyField(blank=True, related_name='phases', to='tasks.Solution'),
        ),
        migrations.AddField(
            model_name='phase',
            name='status',
            field=models.TextField(blank=True, choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Next', 'Next'), ('Final', 'Final')], null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='phases', to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.Competition'),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='competitions_im_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phase',
            name='ingestion_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_ingestion_programs', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='input_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_input_datas', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='public_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_public_datas', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='reference_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_reference_datas', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='scoring_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_scoring_programs', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='starting_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_starting_kits', to='datasets.Data'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='leaderboards.Leaderboard'),
        ),
        migrations.AlterField(
            model_name='submissiondetails',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='competitions.Submission'),
        ),
    ]
