# Generated by Django 2.2.13 on 2020-11-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0024_auto_20201021_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_specific_task_re_run',
            field=models.BooleanField(default=False),
        ),
    ]
