# Generated by Django 2.1.2 on 2019-01-31 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_auto_20190128_2350'),
        ('competitions', '0023_auto_20190116_1921'),
    ]

    operations = [
    ]
