# Generated by Django 2.2.13 on 2020-11-10 19:32
# Manual edit on 2023-08-22 by Adrien Pavao

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def set_blank_fact_sheet_to_null(apps, schema_editor):
    Competition = apps.get_model('competitions', 'Competition')
    for comp in Competition.objects.all():
        if comp.fact_sheet == "":
            comp.fact_sheet = None
            comp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_submission_is_specific_task_re_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='fact_sheet',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, max_length=4096, null=True),
        ),
        migrations.RunPython(set_blank_fact_sheet_to_null, migrations.RunPython.noop),
    ]
