# Generated by Django 2.1.2 on 2019-01-30 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0025_auto_20190128_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='created_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('denied', 'denied'), ('approved', 'approved'), ('pending', 'pending')], default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Submitting', 'Submitting'), ('Submitted', 'Submitted'), ('Preparing', 'Preparing'), ('Running', 'Running'), ('Scoring', 'Scoring'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Submitting', max_length=128),
        ),
    ]
