# Generated by Django 2.2.13 on 2020-11-10 19:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations

from competitions.models import Competition


class Migration(migrations.Migration):

    def set_blank_fact_sheet_to_null(self, schema_editor):
        for comp in Competition.objects.all():
            if comp.fact_sheet == "":
                comp.fact_sheet = None
                comp.save()

    dependencies = [
        ('competitions', '0025_submission_is_specific_task_re_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='fact_sheet',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, max_length=4096, null=True),
        ),
        migrations.RunPython(set_blank_fact_sheet_to_null),
    ]
