# Generated by Django 2.1.2 on 2019-01-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190111_2126'),
        ('competitions', '0025_auto_20190110_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='task',
        ),
        migrations.AddField(
            model_name='phase',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='phases', to='tasks.Task'),
        ),
    ]
