# Generated by Django 2.1.2 on 2019-01-31 02:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_uuid(apps, schema_editor):
    Competition = apps.get_model('competitions', 'Competition')
    for competition in Competition.objects.all():
        competition.secret_key = uuid.uuid4()
        print(competition.secret_key)
        competition.save()


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_merge_20190131_0221'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_uuid)],
        ),
        migrations.AlterField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Submitting', 'Submitting'), ('Submitted', 'Submitted'), ('Preparing', 'Preparing'), ('Running', 'Running'), ('Scoring', 'Scoring'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='submissiondetails',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='competitions.Submission'),
        ),
    ]
