# Generated by Django 2.1.2 on 2019-01-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190116_2044'),
        ('competitions', '0026_auto_20190111_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='solutions',
            field=models.ManyToManyField(blank=True, related_name='phases', to='tasks.Solution'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='phases', to='tasks.Task'),
        ),
    ]
