# Generated by Django 2.2.13 on 2020-12-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0026_auto_20201110_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phasetaskinstance',
            options={'ordering': ['order_index', 'task']},
        ),
    ]
