# Generated by Django 2.2.13 on 2020-12-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20201211_0350'),
        ('competitions', '0026_auto_20201110_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissions', to='profiles.Organization'),
        ),
    ]
