# Generated by Django 2.1.2 on 2019-01-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0027_auto_20190116_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
