# Generated by Django 2.2.13 on 2020-12-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20201222_2352'),
        ('competitions', '0027_auto_20201219_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissions', to='profiles.Organization'),
        ),
    ]
