# Generated by Django 2.2.13 on 2020-12-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0027_auto_20201219_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='started_when',
            field=models.DateTimeField(null=True),
        ),
    ]
