# Generated by Django 2.1.2 on 2019-01-19 00:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0028_competition_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(default=uuid.UUID('2918695a-1730-4341-ad62-b59ce4afb5d6'), unique=True),
        ),
    ]
