# Generated by Django 2.2.13 on 2021-01-04 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0028_submission_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='leaderboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='leaderboards.Leaderboard'),
        ),
    ]
