# Generated by Django 2.1.2 on 2019-02-19 21:15

from django.db import migrations, models
import storages.backends.s3boto3
import utils.data


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0028_auto_20190214_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='private'), upload_to=utils.data.PathWrapper('submission_result')),
        ),
        migrations.AlterField(
            model_name='submissiondetails',
            name='data_file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket='private'), upload_to=utils.data.PathWrapper('submission_details')),
        ),
    ]
