# Generated by Django 2.2.13 on 2020-12-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0028_submission_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='started_when',
            field=models.DateTimeField(null=True),
        ),
    ]
