# Generated by Django 2.1.2 on 2019-01-19 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_competition_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
