# Generated by Django 2.2.13 on 2021-01-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_auto_20210104_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='started_when',
            field=models.DateTimeField(null=True),
        ),
    ]
