# Generated by Django 2.1.2 on 2019-02-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_auto_20190219_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondetails',
            name='is_scoring',
            field=models.BooleanField(default=False),
        ),
    ]
