# Generated by Django 2.1.2 on 2019-05-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0030_submissiondetails_is_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
