# Generated by Django 2.1.2 on 2019-01-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0030_auto_20190119_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='status',
            field=models.TextField(blank=True, choices=[('Previous', 'Previous'), ('Current', 'Current'), ('Next', 'Next'), ('Final', 'Final')], null=True),
        ),
    ]
