# Generated by Django 2.1.2 on 2019-05-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0029_auto_20190429_2139'),
        ('competitions', '0030_submissiondetails_is_scoring'),
    ]

    operations = [
    ]
