# Generated by Django 2.1.2 on 2019-05-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0031_competition_description'),
        ('competitions', '0029_auto_20190429_2139'),
    ]

    operations = [
    ]
