# Generated by Django 2.2.17 on 2023-05-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0031_auto_20230504_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='worker_hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
