# Generated by Django 2.1.2 on 2019-05-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0031_merge_20190520_2141'),
        ('competitions', '0031_auto_20190521_1850'),
    ]

    operations = [
    ]
