# Generated by Django 2.1.2 on 2019-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0031_auto_20190521_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_migrating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='auto_migration',
            field=models.BooleanField(default=False),
        ),
    ]
