# Generated by Django 2.1.2 on 2019-06-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0032_auto_20190604_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_migrated',
            field=models.BooleanField(default=False),
        ),
    ]
