# Generated by Django 2.1.2 on 2019-01-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0032_auto_20190125_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='has_max_submissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='max_submissions_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='max_submissions_per_person',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
