# Generated by Django 2.2.17 on 2023-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0032_submission_worker_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='report',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='reward',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
