# Generated by Django 2.1.2 on 2019-06-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0032_merge_20190528_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='ignore_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='competitions.Submission'),
        ),
    ]
