# Generated by Django 2.2.17 on 2023-07-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0032_submission_worker_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='reward',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
