# Generated by Django 2.2.17 on 2023-06-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0007_auto_20230609_1738'),
        ('competitions', '0032_submission_worker_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='public_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_public_data', to='datasets.Data'),
        ),
        migrations.AddField(
            model_name='phase',
            name='starting_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_starting_kit', to='datasets.Data'),
        ),
    ]
