# Generated by Django 2.2.17 on 2023-07-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0032_submission_worker_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='reward',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='tasks.Task'),
        ),
    ]
