# Generated by Django 2.1.2 on 2019-06-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0032_auto_20190523_1836'),
        ('competitions', '0032_merge_20190528_2221'),
    ]

    operations = [
    ]
