# Generated by Django 2.1.2 on 2019-06-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0032_merge_20190528_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='chahub_data_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='chahub_needs_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='chahub_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
