# Generated by Django 2.2.17 on 2023-06-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0032_submission_worker_hostname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='is_final_phase',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='status',
        ),
    ]
