# Generated by Django 2.1.2 on 2019-01-25 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0033_auto_20190125_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionparticipant',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.Competition'),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
