# Generated by Django 2.1.2 on 2019-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0033_submission_is_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='has_been_migrated',
            field=models.BooleanField(default=False),
        ),
    ]
