# Generated by Django 2.2.17 on 2023-07-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0033_auto_20230617_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='tasks.Task'),
        ),
    ]
