# Generated by Django 2.1.2 on 2019-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0009_remove_submissionscore_submission'),
        ('competitions', '0033_auto_20190620_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='scores',
            field=models.ManyToManyField(related_name='submissions', to='leaderboards.SubmissionScore'),
        ),
    ]
