# Generated by Django 2.2.17 on 2023-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0034_auto_20230727_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='reward',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
