# Generated by Django 2.2.17 on 2023-08-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0034_auto_20230727_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='test_column',
            field=models.IntegerField(default=0),
        ),
    ]
