# Generated by Django 2.2.17 on 2023-08-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
        ('competitions', '0035_auto_20230806_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='queues.Queue'),
        ),
    ]
