# Generated by Django 2.1.2 on 2019-06-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0035_auto_20190612_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='created_by_migration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='competitions.Phase'),
        ),
    ]
