# Generated by Django 2.2.17 on 2023-08-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0035_auto_20230815_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='report',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='reward',
        ),
        migrations.AddField(
            model_name='competition',
            name='test_column',
            field=models.IntegerField(default=0),
        ),
    ]
