# Generated by Django 2.2.17 on 2023-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0036_submission_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='max_submissions_per_day',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='max_submissions_per_person',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
