# Generated by Django 2.1.2 on 2019-06-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0036_submission_created_by_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created_by_migration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrated_submissions', to='competitions.Phase'),
        ),
    ]
