# Generated by Django 2.2.17 on 2023-08-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0037_auto_20230826_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='make_input_data_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='make_programs_available',
            field=models.BooleanField(default=False),
        ),
    ]
