# Generated by Django 2.1.2 on 2019-06-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0033_auto_20190611_1957'),
        ('competitions', '0037_auto_20190627_2047'),
    ]

    operations = [
    ]
