# Generated by Django 2.1.2 on 2019-07-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0038_merge_20190627_2215'),
        ('competitions', '0034_submission_scores'),
    ]

    operations = [
    ]
