# Generated by Django 2.2.17 on 2023-09-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0038_auto_20230827_2303'),
        ('competitions', '0038_auto_20230830_1631'),
    ]

    operations = [
    ]
