# Generated by Django 2.2.17 on 2023-11-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0039_merge_20230906_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionWhiteListEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition')),
            ],
        ),
    ]
