# Generated by Django 2.2.17 on 2023-11-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0039_merge_20230906_1305'),
        ('competitions', '0035_auto_20230914_1319'),
    ]

    operations = [
    ]
