# Generated by Django 2.2.17 on 2023-11-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0039_merge_20230906_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='has_max_submissions',
            field=models.BooleanField(default=True),
        ),
    ]
