# Generated by Django 2.1.2 on 2019-07-30 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0039_merge_20190712_2237'),
        ('competitions', '0040_remove_submission_ignore_total'),
    ]

    operations = [
    ]
