# Generated by Django 2.2.17 on 2023-11-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0041_auto_20231112_1446'),
        ('competitions', '0040_auto_20231113_1103'),
    ]

    operations = [
    ]
