# Generated by Django 2.1.2 on 2019-08-08 18:59

from django.db import migrations, models
import storages.backends.s3boto3
import utils.data


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0041_merge_20190730_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='result',
        ),
        migrations.AddField(
            model_name='submission',
            name='prediction_result',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='private'), upload_to=utils.data.PathWrapper('prediction_result')),
        ),
        migrations.AddField(
            model_name='submission',
            name='scoring_result',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='private'), upload_to=utils.data.PathWrapper('scoring_result')),
        ),
    ]
