# Generated by Django 2.1.2 on 2019-08-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0041_merge_20190730_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
