# Generated by Django 2.1.2 on 2019-08-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0041_merge_20190730_2316'),
        ('competitions', '0041_auto_20190729_1917'),
    ]

    operations = [
    ]
