# Generated by Django 2.1.2 on 2019-08-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0042_competition_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='registration_required',
        ),
    ]
