# Generated by Django 2.2.17 on 2023-12-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0042_merge_20231120_1551'),
        ('competitions', '0035_auto_20230914_1319'),
    ]

    operations = [
    ]
