# Generated by Django 2.2.17 on 2023-12-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0040_merge_20231123_1456'),
        ('competitions', '0043_merge_20231213_0948'),
    ]

    operations = [
    ]
