# Generated by Django 2.1.2 on 2019-09-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0042_merge_20190809_2038'),
        ('competitions', '0043_competition_docker_image'),
    ]

    operations = [
    ]
