# Generated by Django 2.1.2 on 2019-09-24 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0044_merge_20190813_0336'),
        ('competitions', '0044_merge_20190830_2315'),
    ]

    operations = [
    ]
