# Generated by Django 2.2.17 on 2024-01-29 23:14

from django.db import migrations, models
import utils.data


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0044_merge_20231221_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='logo_icon',
            field=models.ImageField(blank=True, null=True, upload_to=utils.data.PathWrapper('logos', manual_override=True)),
        ),
    ]
