# Generated by Django 2.2.17 on 2024-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0044_merge_20231221_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='auto_run_submissions',
            field=models.BooleanField(default=True),
        ),
    ]
