# Generated by Django 2.1.2 on 2019-09-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0044_merge_20190809_2319'),
        ('competitions', '0045_merge_20190924_2316'),
    ]

    operations = [
    ]
