# Generated by Django 2.2.17 on 2024-02-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0045_competition_auto_run_submissions'),
        ('competitions', '0045_auto_20240129_2314'),
    ]

    operations = [
    ]
