# Generated by Django 2.2.17 on 2024-03-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0046_merge_20240222_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='can_participants_make_submissions_public',
            field=models.BooleanField(default=True),
        ),
    ]
