# Generated by Django 2.2.17 on 2024-04-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0047_competition_can_participants_make_submissions_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='show_detailed_results_in_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='show_detailed_results_in_submission_panel',
            field=models.BooleanField(default=True),
        ),
    ]
