# Generated by Django 2.2.17 on 2024-11-18 11:06

from django.db import migrations, models
import utils.data

# New
from storages.backends.s3boto3 import S3Boto3Storage


class _MigrationPrivateStorage(S3Boto3Storage):
    bucket_name = 'private'


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0048_auto_20240401_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='participants_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='submissions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='detailed_result',
            field=models.FileField(blank=True, null=True, storage=_MigrationPrivateStorage(), upload_to=utils.data.PathWrapper('detailed_result')),
        ),
        migrations.AlterField(
            model_name='submission',
            name='prediction_result',
            field=models.FileField(blank=True, null=True, storage=_MigrationPrivateStorage(), upload_to=utils.data.PathWrapper('prediction_result')),
        ),
        migrations.AlterField(
            model_name='submission',
            name='scoring_result',
            field=models.FileField(blank=True, null=True, storage=_MigrationPrivateStorage(), upload_to=utils.data.PathWrapper('scoring_result')),
        ),
        migrations.AlterField(
            model_name='submissiondetails',
            name='data_file',
            field=models.FileField(storage=_MigrationPrivateStorage(), upload_to=utils.data.PathWrapper('submission_details')),
        ),
    ]
