# Generated by Django 2.2.28 on 2024-11-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0049_auto_20241118_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='participants_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
