# Generated by Django 2.2.28 on 2024-12-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0050_auto_20241128_0814'),
        ('competitions', '0049_auto_20241121_0922'),
    ]

    operations = [
    ]
