# Generated by Django 2.2.28 on 2025-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0052_auto_20250129_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='forum_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
