# Generated by Django 2.2.28 on 2025-03-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0053_auto_20250218_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiondetails',
            name='file_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
