# Generated by Django 2.2.28 on 2025-03-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0054_auto_20250324_0622'),
        ('competitions', '0053_competition_forum_enabled'),
    ]

    operations = [
    ]
