# Generated by Django 2.2.28 on 2025-03-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0054_auto_20250321_1341'),
        ('competitions', '0055_merge_20250324_0650'),
    ]

    operations = [
    ]
