# Generated by Django 2.2.28 on 2025-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0056_merge_20250324_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='hide_score_output',
            field=models.BooleanField(default=False),
        ),
    ]
