# Generated by Django 2.2.28 on 2025-06-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0058_phase_hide_prediction_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='chahub_data_hash',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='chahub_needs_retry',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='chahub_timestamp',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='chahub_data_hash',
        ),
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='chahub_needs_retry',
        ),
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='chahub_timestamp',
        ),
        migrations.RemoveField(
            model_name='competitionparticipant',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='chahub_data_hash',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='chahub_needs_retry',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='chahub_timestamp',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='chahub_data_hash',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='chahub_needs_retry',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='chahub_timestamp',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='deleted',
        ),
    ]
