# Generated by Django 4.2.23 on 2025-09-08 12:32

from django.db import migrations, models
import utils.data
import utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0058_phase_hide_prediction_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="fact_sheet",
            field=models.JSONField(
                blank=True, default=None, max_length=4096, null=True
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="competitioncreationtaskstatus",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="competitiondump",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="competitionparticipant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="competitionwhitelistemail",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="phasetaskinstance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="detailed_result",
            field=models.FileField(
                blank=True,
                null=True,
                storage=utils.storage.PrivateStorageClass(),
                upload_to=utils.data.PathWrapper("detailed_result"),
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="fact_sheet_answers",
            field=models.JSONField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="prediction_result",
            field=models.FileField(
                blank=True,
                null=True,
                storage=utils.storage.PrivateStorageClass(),
                upload_to=utils.data.PathWrapper("prediction_result"),
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="scoring_result",
            field=models.FileField(
                blank=True,
                null=True,
                storage=utils.storage.PrivateStorageClass(),
                upload_to=utils.data.PathWrapper("scoring_result"),
            ),
        ),
        migrations.AlterField(
            model_name="submissiondetails",
            name="data_file",
            field=models.FileField(
                storage=utils.storage.PrivateStorageClass(),
                upload_to=utils.data.PathWrapper("submission_details"),
            ),
        ),
        migrations.AlterField(
            model_name="submissiondetails",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
