# Generated by Django 3.2.0 on 2026-03-07 00:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import storages.backends.s3boto3
import utils.data


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0059_auto_20250623_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='model_card_visibility',
            field=models.CharField(
                choices=[('public', 'Public'), ('private', 'Private')],
                default='private',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='submission',
            name='model_card',
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3boto3.S3Boto3Storage(),
                upload_to=utils.data.PathWrapper('model_cards'),
            ),
        ),
        migrations.AddField(
            model_name='submission',
            name='model_card_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='model_card_file_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='model_card_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='model_card_status',
            field=models.CharField(
                choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('PARSED', 'Parsed'), ('FAILED', 'Failed')],
                default='NONE',
                max_length=20,
            ),
        ),
    ]
