# Generated by Django 4.2.25 on 2025-12-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "competitions",
            "0059_alter_competition_fact_sheet_alter_competition_id_and_more",
        ),
        ("competitions", "0059_auto_20250623_1341"),
    ]

    operations = []
