# Generated by Django 5.2.14 on 2026-06-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0060_merge_20251212_0942'),
        ('profiles', '0022_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='participant_groups',
            field=models.ManyToManyField(blank=True, help_text='Competition owner being able to create groups of users.', related_name='competitions', to='profiles.customgroup', verbose_name='group of participants'),
        ),
    ]
