# Generated by Django 5.2.14 on 2026-06-17 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0061_competition_participant_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("endpoint", models.CharField(max_length=64)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField(default=0)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("created_when", models.DateTimeField(auto_now_add=True)),
                ("updated_when", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="competitions.submission",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_when"], name="competition_created_672c32_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["owner", "endpoint", "key"],
                        name="unique_idempotency_owner_endpoint_key",
                    ),
                ],
            },
        ),
    ]
