# Generated by Django 5.2.15 on 2026-08-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0061_competition_participant_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="enable_human_in_the_loop",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Submitting", "Submitting"),
                    ("Submitted", "Submitted"),
                    ("Preparing", "Preparing"),
                    ("Running", "Running"),
                    ("Scoring", "Scoring"),
                    ("Awaiting validation", "Awaiting validation"),
                    ("Cancelled", "Cancelled"),
                    ("Finished", "Finished"),
                    ("Failed", "Failed"),
                ],
                default="Submitting",
                max_length=128,
            ),
        ),
    ]
