# Generated by Django 5.2.14 on 2026-06-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0062_idempotencyrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="worker_attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
