# Generated by Django 5.2.13 on 2026-08-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0062_competition_enable_human_in_the_loop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='allow_robot_submissions',
        ),
    ]
