# Generated by Django 5.2.17 on 2026-10-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0063_remove_competition_allow_robot_submissions'),
        ('profiles', '0025_customgroup_is_selectable_by_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='selected_groups',
            field=models.ManyToManyField(blank=True, related_name='submissions_selected_in', to='profiles.customgroup'),
        ),
    ]
