# Generated by Django 2.2.13 on 2020-11-20 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_forums_for_competitions(apps, schema_editor):
    Competition = apps.get_model('competitions', 'Competition')
    Forum = apps.get_model('forums', 'Forum')
    for competition in Competition.objects.all():
        Forum.objects.create(competition=competition)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0026_auto_20201110_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='competitions.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('last_post_date', models.DateTimeField(blank=True, null=True)),
                ('pinned_date', models.DateTimeField(blank=True, null=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forums.Forum')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_post_date',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('content', models.TextField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forums.Thread')),
            ],
        ),
        migrations.RunPython(create_forums_for_competitions),
    ]
