# Generated by Django 4.2.23 on 2025-09-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
