# Generated by Django 2.2.17 on 2023-08-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStorageDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backups_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('others_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('at_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionStorageDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_when', models.DateTimeField()),
                ('competition_type', models.CharField(choices=[('competition', 'competition'), ('benchmark', 'benchmark')], default='competition', max_length=128)),
                ('datasets_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('at_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageUsageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=255)),
                ('at_date', models.DateTimeField()),
                ('total_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('competitions_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('users_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('admin_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStorageDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('datasets_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('submissions_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('at_date', models.DateTimeField()),
            ],
        ),
    ]
