# Generated by Django 2.2.17 on 2023-09-14 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0035_auto_20230914_1319'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStorageDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backups_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('at_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUsageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=255)),
                ('total_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('competitions_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('users_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('admin_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('orphaned_file_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('at_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStorageDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasets_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('submissions_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('at_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionStorageDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasets_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('at_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.Competition')),
            ],
        ),
    ]
